### PR TITLE
Avatar

### PR DESCRIPTION
**Pull request by VedanthB**
- added reset styles 
- added root variables for colors and base margin, padding etc,
- added bg-color and text-color util classes 
- added avatar and img classes
avatar screenshots

### CODE REVIEW

**Comment by ashishnnnnn** [comment]
It looks good :) ..
Just one suggestion.. Try to host it so that we can see the changes live :)

**Comment by SukanyaSen530** [comment]
Looks good, suggestion - try to separate the common styles into a folder :)

**Review by SukanyaSen530 — APPROVED** [review]

**Review by Prabhav-Sharma — COMMENTED** [review]
Looks good, you can merge it

**Review by Hardiegogo — APPROVED** [review]
It looks good. You can merge it.

**Pull request merged**
